export enum ADDRESS_TYPE {
  DEPOSIT = 1,
  WITHDRAW = 2,
}
export enum PRIVATE_TOKEN_CURRENCY_TYPE {
  ETH = 1,
  BTC = 2,
  ERC20 = 3,
  BNB = 4,
  BNB_BEP2 = 5,
  USD = 6,
}

export enum CRYPTO_SYMBOL {
  PRV = 'PRV',
  BTC = 'BTC',
  ETH = 'ETH',
  BNB = 'BNB',
  USD = 'USD',
  KCS = 'KCS',
  TOMO = 'TOMO',
  NEO = 'NEO',
  XMR = 'XMR',
  ZEN = 'ZEN',
  ZCL = 'ZCL',
  ZEC = 'ZEC',
  VOT = 'VOT',
  VTC = 'VTC',
  SNG = 'SNG',
  XRP = 'XRP',
  XRB = 'XRB',
  QTUM = 'QTUM',
  PTS = 'PTS',
  PPC = 'PPC',
  GAS = 'GAS',
  NMC = 'NMC',
  MEC = 'MEC',
  LTC = 'LTC',
  KMD = 'KMD',
  HUSH = 'HUSH',
  GRLC = 'GRLC',
  FRC = 'FRC',
  DOGE = 'DOGE',
  DGB = 'DGB',
  DCR = 'DCR',
  CLO = 'CLO',
  BTG = 'BTG',
  BCH = 'BCH',
  BIO = 'BIO',
  BVC = 'BVC',
  BKX = 'BKX',
  AUR = 'AUR',
  ZIL = 'ZIL',
}
