export const MAX_PDEX_TRADE_STEPS = 1
export const DEFAULT_FEE_PER_KB_HUMAN_AMOUNT = 0.000000001 // in nano
export const DEFAULT_NANO_MULTIPLER = 1e9
export const DEFAULT_FEE_PER_KB = DEFAULT_FEE_PER_KB_HUMAN_AMOUNT * DEFAULT_NANO_MULTIPLER // in nano
export const MAX_TX_SIZE = 100
export const MAX_FEE_PER_TX = DEFAULT_FEE_PER_KB * MAX_TX_SIZE
export const MAX_DEX_FEE = MAX_FEE_PER_TX * MAX_PDEX_TRADE_STEPS
